[[headers]]
  for = "/assets/*"
  [headers.values]
    "Content-Type" = "application/javascript"

[[headers]]
  for = "/assets/css/*"
  [headers.values]
    "Content-Type" = "text/css"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18" 